"""empty message

Revision ID: c75ccbf95539
Revises: 
Create Date: 2025-10-06 20:52:47.357250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75ccbf95539'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('job_id', sa.Integer(), nullable=False, comment='工号（登录用）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('password', sa.String(length=50), nullable=False, comment='密码'),
    sa.Column('gender', sa.String(length=2), nullable=True, comment='性别（男/女）'),
    sa.Column('duty', sa.String(length=20), nullable=True, comment='职务'),
    sa.Column('type', sa.String(length=8), nullable=True, comment='人员类型（工作人员/管理员）'),
    sa.CheckConstraint("gender IN ('男', '女')", name='check_gender'),
    sa.CheckConstraint("type IN ('工作人员', '管理员')", name='check_user_type'),
    sa.PrimaryKeyConstraint('job_id'),
    comment='用户信息表'
    )
    op.create_table('Attendance',
    sa.Column('Ad_id', sa.Integer(), autoincrement=True, nullable=False, comment='序号'),
    sa.Column('adjob_id', sa.Integer(), nullable=True, comment='关联工号'),
    sa.Column('begin_date', sa.DateTime(), nullable=True, comment='签到时间'),
    sa.Column('begin_type', sa.String(length=20), nullable=True, comment='签到情况（正常、迟到、未签）'),
    sa.Column('over_date', sa.DateTime(), nullable=True, comment='签退时间'),
    sa.Column('over_type', sa.String(length=20), nullable=True, comment='签退情况（正常、早退、未签）'),
    sa.ForeignKeyConstraint(['adjob_id'], ['Users.job_id'], ),
    sa.PrimaryKeyConstraint('Ad_id'),
    comment='考勤记录表'
    )
    op.create_table('Leave_tb',
    sa.Column('ltb_id', sa.Integer(), autoincrement=True, nullable=False, comment='序号'),
    sa.Column('job_id', sa.Integer(), nullable=False, comment='申请人工号'),
    sa.Column('ltb_txt', sa.Text(), nullable=True, comment='申请理由'),
    sa.Column('handler_id', sa.Integer(), nullable=False, comment='审核员工号'),
    sa.Column('ltb_type', sa.String(length=30), nullable=True, comment='申请状态（如：待审核、已批准、已拒绝）'),
    sa.Column('application_time', sa.DateTime(), nullable=True, comment='申请时间'),
    sa.Column('audit_time', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('ltb_day', sa.Integer(), nullable=True, comment='请假天数'),
    sa.Column('vacation_time', sa.DateTime(), nullable=True, comment='销假时间'),
    sa.Column('overdue_type', sa.String(length=2), nullable=True, comment='逾期情况（是/否）'),
    sa.Column('overdue_day', sa.Integer(), nullable=True, comment='逾期天数'),
    sa.CheckConstraint("overdue_type IN ('是', '否')", name='check_overdue_type'),
    sa.ForeignKeyConstraint(['handler_id'], ['Users.job_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['Users.job_id'], ),
    sa.PrimaryKeyConstraint('ltb_id'),
    comment='请假情况表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Leave_tb')
    op.drop_table('Attendance')
    op.drop_table('Users')
    # ### end Alembic commands ###
